main: com.stgaming.mc.Initialize
name: STGSafeConnector
version: 0.0.1
api-version: 1.15
description: SynTacs Gaming's Minecraft Plugin
author: STGaming SynTacs
commands:
  login:
    description: Login Command
    usage: /<command>